name: XPI Generation
on: [push]

jobs:
   xpi-job:
       name: XPI Gen Job
       runs-on: ubuntu-latest
       steps:
           - name: Create XPI file
             run: cd src && zip -r cmunits.xpi . && mv cmunits.xpi ../
